---
  - name: Install, Start and Enable Nginx
    hosts: app1
    become: true

    tasks:
      - name: Install Nginx
        yum:
          name: nginx
          state: latest

      - name: Start and Enable Nginx
        systemd:
          name: nginx
          enabled: yes
          state: started